#!/usr/bin/env bash

tmpfile=$HOME/.config/neomutt/tmpfile

if \[ -z "$1" \]; then
    yazi "$@" --cwd-file="$tmpfile" &&
        sed -i 's/ /^V /g' $tmpfile &&
        echo "$(awk 'BEGIN {printf "%s", "push "} {printf "%s", "<save-entry>\""$0"\"<enter>"}' $tmpfile)" >$tmpfile
elif \[ "$1" == "clean" \]; then
    rm $tmpfile
fi
