name: Check formatting
on:
  push:
    branches:
      - main
      - devel
jobs:
  format:
    name: Check formatting
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@v17
        with:
          extra-conf: |
            auto-optimise-store = true
      - run: nix run nixpkgs#nixfmt-tree -- --ci --fail-on-change .
