name: Check formatting
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - devel
jobs:
  format:
    name: Formatting
    runs-on: alpine-latest
    steps:
      - name: Install Lix
        uses: actions/install-lix@v1
      - name: Checkout flake
        uses: actions/checkout@v6
      - name: Check formatting of Nix code
        run: nix run nixpkgs#nixfmt-tree -- --ci .
