name: Check formatting
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - devel
jobs:
  format:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Install required packages
        run: |
          nix profile install nixpkgs#nodejs_24
        uses: actions/checkout@v4
        uses: https://github.com/cachix/install-nix-action@v31
        run: nix run nixpkgs#nixfmt-tree -- --ci .
