name: Check formatting
on:
  push:
    branches:
      - main
      - devel
jobs:
  test:
    runs-on: debian-latest
    container: nixpkgs/nix-flakes:latest-x86_64-linux
    steps:
      - name: Install Node.js in environment
        run: nix profile install nixpkgs#nodejs_24
      - uses: actions/checkout@v4
      - run: nix run nixpkgs#nixfmt-tree -- --ci .
