{
  imports = [
    ./autoclose.nix
    ./blink-cmp.nix
    ./conform-nvim.nix
    ./diffview.nix
    ./gitsigns.nix
    ./hardtime.nix
    ./lint.nix
    ./lsp.nix
    ./plenary.nix
    ./markview.nix
    ./molten.nix
    ./neogit.nix
    ./nix.nix
    ./no-neck-pain.nix
    ./nvim-surround.nix
    ./octo.nix
    ./oil.nix
    ./quarto.nix
    ./telescope.nix
    ./tmux-navigator.nix
    ./treesitter.nix
    ./vim-be-good.nix
    ./web-devicons.nix
    ./yarepl.nix
  ];
}
