# Sync repo to the Codeberg mirror
name: Mirror repo to Codeberg
on:
  push:
    branches:
      - "**"
  pull_request_target:
    types:
      - closed
  workflow_dispatch:

jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: "https://codeberg.org/arsann/nixos.git"
          GIT_USERNAME: arsann
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
