name: "nix-flake-check"
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: /nix/store
          key: ${{ runner.os }}-nix
          restore-keys: |
            ${{ runner.os }}-nix
      - uses: cachix/install-nix-action@v30
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix flake check --show-trace
